version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=life_organizer
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy  # <-- Agrega esta línea

  db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: life_organizer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10